### ISSUE TITLE
Create real donate page

### ISSUE THREAD

**Issue by krusynth** [opengovfoundation/opengovfoundation-theme#14]
With crafted content and explaining ways to give.  The link will suffice for now, but this needs to happen eventually

**Comment by krusynth** [comment]
Relatedly, we should customize the text on the Paypal donation page to explain that their gift is tax-deductable.

**Comment by abartnick** [comment]
Content:

The OpenGov Foundation is a nonpartisan, nonprofit 501(c)(3) organization building a 21st century democracy by bridging the gap between citizens and government. We work with elected officials, civil servants, and private citizens across the country and at all levels of government to build smarter, more inclusive, and more open governments.

Most of our services are open source and available online, which means that anyone can use them for free. That’s why we count on support from people like you in order to keep operating. Can you join fellow open government supporters from across the country and chip in to support The OpenGov Foundation?

Disclaimer:

The OpenGov Foundation is a nonpartisan, nonprofit 501(c)(3) organization (EIN 45-4848546). All contributions are tax deductible. You can view our most recent financial report here[LINK--need to upload latest financial report].
